global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "5g_consumer_metrics"
    static_configs:
      - targets: ["host.docker.internal:8000"]
      
rule_files:
  - /etc/prometheus/alerts.yml